Stock_Game/urls.py
from django.urls import path
from . import views
from User import urls

urlpatterns =[

    path('',views.index,name="home"),
    path('main/',views.main_home,name="main"),
    path('stocks/<team_name>/',views.stocks_list,name="stocks"),
    path('portfolio/<team_name>/',views.portfolio,name="stocks"),
    path('ranklist/<team_name>/',views.ranklist,name="stocks"),
    path('stockname/<stock>/',views.stockers,name="stockname"),
    path('createform/',views.Create_team,name="creater"),
    path('getval/<stock>',views.getval,name="getval"),
    path('showname/<team_hel>',views.shownum,name="show"),
    path('join/',views.join,name="join"),
    path('stock_detail/<room_name>/<stock_name>/', views.stock_details, name='stock_details'),
    path('stock_detail/<room_name>/<stock_name>/<current_stock_price>/', views.push_details, name='push_details'),
    path('stock_details/<room_name>/<stock_name>/<current_stock_price>/<no_of_shares>/', views.pull_details, name='pull_details'),
    path('stock_detail/<room_name>/<stock_name>/<current_stock_price>/<no_of_shares>/pred/', views.predict, name='predict'),
    path('stock_detail/<room_name>/<stock_name>/<invested_stock_price>/<current_stock_price>/<no_of_shares>/', views.portfolio_pull, name='portfolio_pull'),
    path('port_push/<room_name>/<stock_name>/<invested_stock_price>/<current_stock_price>/<no_of_shares>/<var>/', views.port_push, name='port_push'),
]

Stock_Trainer/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Stock_Game.urls')),
    path('user/',include('User.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

User/urls.py
from atexit import register
import imp
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from User.views import *
from django.contrib.auth import views as auth_views

urlpatterns=[
    path('',register,name='register'),
    path('subscribe/',subscribe,name='subscribe'),
    path('create-blogs/',PostCreate.as_view(template_name='User/blog.html'),name="create-blog"),
    path('login/',auth_views.LoginView.as_view(template_name='User/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='User/logout.html'),name='logout'),
    path('blogs/',blog_list,name='blog_list'),
    path('upvote/',upvote.as_view(),name='upvote'),
    path('profile/<user>',profile,name='profile'),
    path('addSubscriber/',addSubscriber,name='addSubscriber'),
]

Stock_Game/models.py
from django.db import models
from User.models import Profile, Consultant, Subscribe
# Create your models here.
class Room(models.Model):
    reg_user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    room_name = models.CharField(max_length=30)
    desc=models.CharField(max_length=100)
    ends_in = models.DateField()
    room_money = models.IntegerField()

    def __str__(self):
        return self.room_name

class Join(models.Model):
    reg_user_id = models.ForeignKey(Profile, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    user_money = models.FloatField()

class Stock(models.Model):

    stock_name = models.CharField(max_length=50)
    nse_code = models.CharField(max_length=20)

    def __str__(self):
        return self.nse_code

class Buy(models.Model):

    reg_user_id = models.ForeignKey(Profile, on_delete=models.CASCADE)
    reg_room_id = models.ForeignKey(Room, on_delete=models.CASCADE)
    reg_stock_id = models.ForeignKey(Stock, on_delete=models.CASCADE)
    current_stock_price = models.FloatField()
    no_of_shares = models.IntegerField()

Stock_Game/forms.py
from django import forms
from datetime import date,time
from .models import Room
class CreateForm(forms.ModelForm):
    class Meta:
        model=Room
        widgets = {
            'desc': forms.Textarea(
            attrs={'placeholder': 'Enter description here'}),
            'end_in' :forms.DateField(
                widget=forms.TextInput(
                    attrs={'type': 'date'}
    )
            ),
        }
        exclude=('reg_user',)

Stock_Game/views.py
from django.shortcuts import render, redirect
from nsetools import Nse
import json
from yahoo_fin import stock_info

# x = stock_info.get_live_price("SBIN.NS")

from django.http import JsonResponse
from .models import Room, Buy, Join, Stock, Profile, Consultant, Subscribe
from django.shortcuts import render, redirect, get_object_or_404
import ast
from bs4 import BeautifulSoup as BS
import requests as req
from operator import itemgetter
from .models import Stock, Buy, Room, Join
from User.models import Profile, Subscribe, Consultant
from .forms import CreateForm
from django.contrib import messages
from Stock_Game.lstm import *
import traceback


def index(request):
    return render(request, "Stock_Game/index.html")


# creating a Nse object
# nse = Nse()


def Create_team(request):
    print("GO to hell")
    if request.method == 'POST':
        print("GO to hell")
        form = CreateForm(request.POST, request.FILES)
        if form.is_valid():
            Profile1 = Profile.objects.filter(user=request.user)
            p = form.save(commit=False)
            print("marja")
            p.reg_user = Profile1[0]
            p.save()
            print("Hell")
            post = Join()
            post.reg_user_id = Profile1[0]
            pol = Room.objects.get(id=(p.pk))
            post.room = pol
            post.user_money = pol.room_money
            post.save()
            return redirect('show', p.pk)
        else:
            print(form.errors)
            return render(request, 'Stock_Game/form.html', {'form': form})
    else:
        form = CreateForm()
        return render(request, 'Stock_Game/form.html', {'form': CreateForm})


def shownum(request, team_hel):
    param = {'hex': hex(int(team_hel))}
    return render(request, 'Stock_Game/show.html', param)


def join(request):
    if request.method == 'POST':
        if request.POST.get('content'):
            post = Join()
            Profile1 = Profile.objects.filter(user=request.user)
            post.reg_user_id = Profile1[0]
            k = ast.literal_eval(request.POST.get('content'))
            print(k)
            pol = Room.objects.get(id=k)
            post.room = pol
            post.user_money = pol.room_money
            post.save()
            return redirect('main')
    return redirect('main')


def main_home(request):
    room1 = Room.objects.filter(id=1)
    for i in room1:
        k1 = i
    init = room1[0].room_money
    teams = Join.objects.filter(room=k1)
    print(teams)
    # nse = Nse()
    Profile1 = Profile.objects.filter(user=request.user)
    room2 = Join.objects.filter(reg_user_id=Profile1[0])
    print(room2)
    subs = Subscribe.objects.filter(reg_user=Profile1[0])
    buy2 = Buy.objects.filter(reg_user_id=Profile1[0]).filter(reg_room_id=1)
    sum1 = room2[0].user_money
    sum2 = room2[0].user_money
    print(sum1)
    for j in buy2:
        x = j.reg_stock_id.nse_code + ".NS"
        print(x)
        quote = stock_info.get_live_price(x)
        print(quote)
        sum1 += (quote * j.no_of_shares)
    print(sum1)
    k3 = 1
    for i in teams:
        p = []
        p.append(i.reg_user_id.user.username)
        buy1 = Buy.objects.filter(reg_user_id=i.reg_user_id).filter(reg_room_id=i.room)
        sum = i.user_money
        k2 = -99999;
        for j in buy1:
            x = j.reg_stock_id.nse_code + ".NS"
            print(x)
            quote = stock_info.get_live_price(x)
            sum += (quote * j.no_of_shares)
        if sum > sum1:
            k3 += 1
    print(init)
    param = {'rank': k3, 'avail': sum2, 'profit': round(sum1 - init, 2), 'room': room2, 'subs': subs}
    return render(request, 'Stock_Game/main.html', param)


def stocks_list(request, team_name):
    # nse = Nse()

    stocks = Stock.objects.all()
    print(stocks)
    k = []
    for i in stocks:
        d = dict()
        quote = stock_info.get_live_price(i.nse_code + ".NS")
        d['name'] = i.stock_name
        d['Price'] = quote
        d['id'] = team_name
        d['nse_code'] = i.nse_code
        k.append(d)
    param = {'k': k}
    return render(request, 'Stock_Game/Stock_list.html', param)


def ranklist(request, team_name):
    print(team_name)
    room1 = Room.objects.filter(id=team_name)
    print(room1)
    for i in room1:
        k1 = i
    teams = Join.objects.filter(room=k1)
    k = []
    # nse = Nse()
    for i in teams:
        p = []
        p.append(i.reg_user_id.user.username)
        buy1 = Buy.objects.filter(reg_user_id=i.reg_user_id).filter(reg_room_id=i.room)
        sum = i.user_money
        print(i.user_money)
        k2 = -99999;
        for j in buy1:
            quote = stock_info.get_live_price(j.reg_stock_id.nse_code + ".NS")
            if k2 < quote * j.no_of_shares:
                p1 = j.reg_stock_id.stock_name
            sum += (quote * j.no_of_shares)
            print(quote)
            print(j.no_of_shares)

            print(sum)
        p.append(int(sum))
        p.append(p1)
        k.append(p)
    k.sort(key=lambda x: x[1], reverse=True)
    p2 = []
    k3 = 1
    for i in k:
        h1 = dict()
        h1['rank'] = k3
        h1['name'] = i[0]
        h1['sum'] = i[1]
        k3 += 1
        h1['Stock'] = i[2]
        p2.append(h1)
    print(p2)
    param = {'k': p2}
    return render(request, 'Stock_Game/stocker.html', param)


def portfolio(request, team_name):
    us = request.user
    # nse = Nse()
    Room1 = Room.objects.filter(id=team_name)
    init = Room1[0].room_money
    name = Room1[0].room_name
    id1 = Room1[0].id
    Profile1 = Profile.objects.filter(user=request.user)
    for i in Profile1:
        k = i
    Buy1 = Buy.objects.filter(reg_user_id=k.id).filter(reg_room_id=team_name)
    k = []
    sums = 0
    inv = 0
    sum = 0
    var = 0
    for i in Buy1:
        sums = 0
        k2 = dict()
        k2['stock_nse'] = i.reg_stock_id.nse_code
        k2['stock_name'] = i.reg_stock_id.stock_name
        k2['no_of_shares'] = i.no_of_shares
        quote = stock_info.get_live_price(i.reg_stock_id.nse_code + ".NS")
        k2['old_price'] = i.current_stock_price
        k2['Current_price'] = quote
        k2['profit'] = round((quote- i.current_stock_price) * i.no_of_shares, 2)
        sum = sum + (quote) * i.no_of_shares
        sums = sums + (quote) * i.no_of_shares
        inv = inv + i.current_stock_price * i.no_of_shares
        print(inv)
        k2['sums'] = sums
        k2['var'] = var
        var = var + 1
        k.append(k2)
    print(init)
    param = {'k': k, 'money_left': (init - inv), 'Profit': round(sum - inv, 2), 'Initial': init, 'name': name,
             'id': id1}
    return render(request, 'Stock_Game/portfolio.html', param)


# Create your views here.
def stockers(request, stock):
    print(stock)
    # nse = Nse()
    quote = stock_info.get_live_price(stock + ".NS")
    param = {'stock_name': quote['companyName'], 'Stock_price': quote}
    return render(request, 'Stock_Game/stocker.html', param)


def stock_details(request, room_name, stock_name):
    # nse = Nse()
    quote = stock_info.get_live_price(stock_name + ".NS")
    x = Room.objects.filter(id=room_name)
    x = x[0].room_name
    print(room_name)

    context = {
        'room_id': room_name,
        'room_name': x,
        'stock_name': stock_name,
        'current_stock_price': quote,
    }
    p = Profile.objects.filter(user=request.user)[0]
    room_b = Join.objects.filter(reg_user_id=p, room=room_name)
    context['room_balance'] = room_b[0].user_money
    context['no_of_shares'] = 0;
    print(p, x, int(room_name), stock_name)
    x = Stock.objects.filter(nse_code=stock_name)[0].stock_name
    context['temp'] = x
    return render(request, 'Stock_Game/stock_details.html', context)


def getval(request, stock):
    # TO GET THE TPYE OF CLASS
    # HERE 'a' STANDS FOR ANCHOR TAG IN WHICH NEWS IS STORED
    # nse = Nse()
    quote = stock_info.get_live_price(stock + ".NS")
    contem = {
        'code': quote,
    }
    return JsonResponse(contem)


def push_details(request, room_name, stock_name, current_stock_price):
    try:
        # print("Mai hi hoon")
        request.session['POSTVALUES'] = request.POST.copy(),

        post_values = request.session.get('POSTVALUES')
        # print(post_values)

        x = post_values[0]
        no_of_share = x['quantity'],
        total_amount = x['output'],

        pr = Profile.objects.filter(user=request.user)[0]
        ro = Room.objects.filter(id=room_name)[0]
        st = Stock.objects.filter(nse_code=stock_name)[0]
        print(type(current_stock_price), current_stock_price)

        imp = Join.objects.filter(reg_user_id=pr, room=ro)

        upd = imp[0].user_money - float(total_amount[0])
        print(upd)

        if request.method == 'POST':
            if (Buy.objects.filter(reg_user_id=pr, reg_room_id=ro, reg_stock_id=st,
                                   current_stock_price=current_stock_price).exists()):
                x = Buy.objects.get(reg_user_id=pr, reg_room_id=ro, reg_stock_id=st,
                                    current_stock_price=current_stock_price)
                x = x.no_of_shares
                y = int(x) + int(no_of_share[0])
                Buy.objects.filter(reg_user_id=pr, reg_room_id=ro, reg_stock_id=st,
                                   current_stock_price=current_stock_price).update(no_of_shares=y)

            else:
                Buy.objects.create(reg_user_id=pr, reg_room_id=ro, reg_stock_id=st,
                                   current_stock_price=current_stock_price, no_of_shares=no_of_share[0]),

            Join.objects.filter(reg_user_id=pr, room=ro).update(user_money=upd),

        x = '/portfolio/' + room_name + '/'
        return redirect(to=x)

    except:
        traceback.print_exc()
        return redirect('push_details', room_name=room_name, stock_name=stock_name)


def pull_details(request, room_name, stock_name, current_stock_price, no_of_shares):

Stock_Game/templates/Stock_Game/Stock_list.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.104.2">
    <title>Stock List</title>
<link rel="stylesheet" href="{% static 'Stock_Game/css/index.css' %}">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/features/">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
      body{
	margin:0;
	padding:0;
	font-family:"arial",heletica,sans-serif;
	font-size:12px;
    background: #2980b9 url('https://static.tumblr.com/03fbbc566b081016810402488936fbae/pqpk3dn/MRSmlzpj3/tumblr_static_bg3.png') repeat 0 0;
	-webkit-animation: 10s linear 0s normal none infinite animate;
	-moz-animation: 10s linear 0s normal none infinite animate;
	-ms-animation: 10s linear 0s normal none infinite animate;
	-o-animation: 10s linear 0s normal none infinite animate;
	animation: 10s linear 0s normal none infinite animate;

}

@-webkit-keyframes animate {
	from {background-position:0 0;}
	to {background-position: 500px 0;}
}

@-moz-keyframes animate {
	from {background-position:0 0;}
	to {background-position: 500px 0;}
}

@-ms-keyframes animate {
	from {background-position:0 0;}
	to {background-position: 500px 0;}
}

@-o-keyframes animate {
	from {background-position:0 0;}
	to {background-position: 500px 0;}
}

@keyframes animate {
	from {background-position:0 0;}
	to {background-position: 500px 0;}
}
    </style>



    <!-- Custom styles for this template -->
    <link href="features.css" rel="stylesheet">

    <style>
      .avatar {
         vertical-align: middle;
         width: 30px;
         height: 30px;
         border-radius: 50%;
       }
    </style>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/headers/">

    <link href="/docs/5.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

  </head>
  <body>
  <nav class="navbar navbar-light navPad" style="background-color: #377dc34d">
        <div class="container-fluid">
            <a href="/main" style="color: white; text-shadow: 1px 1px 2px black, 0 0 25px red, 0 0 5px blue;" class="navbar-brand logoPad hh66Heading" style="width: 148px;height: 40px;">Stock Trainer</a>
            <div style="padding-top: 5px">
                <img style="margin-right: 5px" src="{% static 'Stock_Game/images/hi5.jpg' %}" alt="Avatar" class="avatar">
                <a style="font-size:18px; color:white; padding-right:40px; padding-top: 5px; margin-top: 5px">Welcome, {{request.user}}</a>
                <a href="/user/logout" style="font-size:18px; color:white; padding-right:40px; text-decoration: none;" onclick="logout()">logout</a>
            </div>
            <script>
                    function logout(){
                    alert('You have logged out successfully')
                    }
                </script>
        </div>
        </nav>
  <main>
	    <div class="container px-4" id="custom-cards">
            <center>
    <h2 class="pb-2 border-bottom" style="color:white">Stocks</h2>
                </center>

    <div class="row row-cols-1 row-cols-lg-1 align-items-stretch g-4 ">
      <div class="col">
        <div class="card card-cover h-100 overflow-hidden text-bg-light rounded-4 shadow-lg">
          <div class="d-flex flex-column h-100 p-5 pb-1 text-black text-shadow-1">
{% for i in k %}
    <div class="row">
              <div class="col">
                <h4>{{i.name}}</h4>
                <h6>Current Price:{{i.Price}}</h6>
              </div>
              <div class="col">

              </div>
              <div class="col">
                <span><a class="btn btn-lg btn-primary" href="/stock_detail/{{i.id}}/{{i.nse_code}}" style="background-color:#3F00FF;padding:7px;margin:10px">View Details</a>
                  </span>
              </div>
            </div>
    {% endfor %}
          </div>
        </div></div>
    </div></div>
        </div>
  </main>

Stock_Game/templates/Stock_Game/form.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.104.2">
    <title>Create Team</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/features/">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }
      body{
	margin:0;
	padding:0;
	font-family:"arial",heletica,sans-serif;
	font-size:12px;
    background: #2980b9 url('https://static.tumblr.com/03fbbc566b081016810402488936fbae/pqpk3dn/MRSmlzpj3/tumblr_static_bg3.png') repeat 0 0;
	-webkit-animation: 10s linear 0s normal none infinite animate;
	-moz-animation: 10s linear 0s normal none infinite animate;
	-ms-animation: 10s linear 0s normal none infinite animate;
	-o-animation: 10s linear 0s normal none infinite animate;
	animation: 10s linear 0s normal none infinite animate;

}

@-webkit-keyframes animate {
	from {background-position:0 0;}
	to {background-position: 500px 0;}
}

@-moz-keyframes animate {
	from {background-position:0 0;}
	to {background-position: 500px 0;}
}

@-ms-keyframes animate {
	from {background-position:0 0;}
	to {background-position: 500px 0;}
}

@-o-keyframes animate {
	from {background-position:0 0;}
	to {background-position: 500px 0;}
}

@keyframes animate {
	from {background-position:0 0;}
	to {background-position: 500px 0;}
}
    </style>


    <!-- Custom styles for this template -->
    <link href="features.css" rel="stylesheet">
  </head>
  <body>
  <main>
	    <div class="container px-4 py-5" id="custom-cards">
    <h2 class="pb-2 border-bottom" style="color:white">Welcome, {{request.user.username}}</h2>
<center>
    <div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5">
      <div class="col">
          </div>
        <div class="col">
        <div class="card card-cover h-100 overflow-hidden text-bg-light rounded-4 shadow-lg">
          <div class="d-flex flex-column h-100 p-5 pb-3 text-black text-shadow-1">
			 <center> <h2>Create New Teams</h2></center>
{% load crispy_forms_tags %}
    <form method="POST">
        {% csrf_token %}
        <div id="div_id_room_name" class="control-group"> <label for="id_room_name" class="control-label requiredField">
                Room name<span class="asteriskField">*</span> </label> <div class="controls"> <input type="text" name="room_name" maxlength="30" class="textinput textInput" required id="id_room_name"> </div> </div> <div id="div_id_desc" class="control-group"> <label for="id_desc" class="control-label requiredField">
                Desc<span class="asteriskField">*</span> </label> <div class="controls"> <textarea name="desc" cols="40" rows="4" placeholder="Enter description here" maxlength="100" class="textarea" required id="id_desc">
</textarea> </div> </div> <div id="div_id_ends_in" class="control-group"> <label for="id_ends_in" class="control-label requiredField">
                Ends in<span class="asteriskField">*</span> </label> <div class="controls"> <input type="date" name="ends_in" class="dateinput" required id="id_ends_in"> </div> </div> <div id="div_id_room_money" class="control-group"> <label for="id_room_money" class="control-label requiredField">
                Room money<span class="asteriskField">*</span> </label> <div class="controls"> <input type="number" name="room_money" class="numberinput" required id="id_room_money"> </div> </div>

        <br/> <center><button class="btn btn-primary" type="submit">Submit</button></center>
    </form>
          </div>
        </div>
      </div>
        </center>
    </div>
        </div>
  </main>

Stock_Game/templates/Stock_Game/nav.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.104.2">

    <style>
      .avatar {
         vertical-align: middle;
         width: 30px;
         height: 30px;
         border-radius: 50%;
       }
    </style>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.2/examples/headers/">

    <link href="/docs/5.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

</head>
</html>
<body>
    <nav class="navbar navbar-light navPad" style="background-color: #377dc34d">
        <div class="container-fluid">
            <a href="/" style="color: white; text-shadow: 1px 1px 2px black, 0 0 25px red, 0 0 5px blue;" class="navbar-brand logoPad hh66Heading" style="width: 148px;height: 40px;">Stock Trainer</a>
            <div style="padding-top: 5px">
                <img style="margin-right: 5px" src="{% static 'Stock_Game/images/hi5.jpg' %}" alt="Avatar" class="avatar">
                <a style="font-size:18px; color:white; padding-right:40px; padding-top: 5px; margin-top: 5px">Welcome, {{request.user}}</a>
                <a href="/user/logout" style="font-size:18px; color:white; padding-right:40px; text-decoration: none;" onclick="logout()">logout</a>
            </div>
            <script>
                    function logout(){
                    alert('You have logged out successfully')
                    }
                </script>
        </div>
        </nav>
</body>